<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-CP18KR3" name="com.Qa.TestScript.TestForm_Testcase" tests="6" failures="1" timestamp="29 Jan 2018 15:16:37 GMT" time="37.422" errors="0">
  <testcase name="validForm" time="6.977" classname="com.Qa.TestScript.TestForm_Testcase"/>
  <testcase name="validForm" time="7.059" classname="com.Qa.TestScript.TestForm_Testcase"/>
  <testcase name="validForm" time="8.372" classname="com.Qa.TestScript.TestForm_Testcase"/>
  <testcase name="invalidcredentails" time="5.040" classname="com.Qa.TestScript.TestForm_Testcase"/>
  <testcase name="checkingSubmitbuttonWithEmptyset" time="4.692" classname="com.Qa.TestScript.TestForm_Testcase"/>
  <testcase name="invalidMaximumcredentials" time="5.282" classname="com.Qa.TestScript.TestForm_Testcase">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [The max length of last name is 20] but found []">
      <![CDATA[java.lang.AssertionError: The following asserts failed:expected [The max length of last name is 20] but found []at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)at com.Qa.TestScript.TestForm_Testcase.invalidMaximumcredentials(TestForm_Testcase.java:92)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- invalidMaximumcredentials -->
</testsuite> <!-- com.Qa.TestScript.TestForm_Testcase -->
